version: '2.0'

services:
  master:
    image: dockersm
    environment:
      JAVA_OPTS: "-Djava.awt.headless=true"
    ports:
      - "5000:5000"
      #- "8084:8080"
      #- "2181:2181"
      #- "3030:3030"
      #- "8081:8081"
      #- "8082:8082"
      #- "8083:8083"
      #- "9092:9092"
    volumes:
      - /var/jenkins_home
      - /var/run/docker.sock:/var/run/docker.sock
      - /usr/bin/docker:/usr/bin/docker
    working_dir: /smashingDSH
    container_name: dockersm
    entrypoint: bash -lc "bundle && smashing start -p 5000 & sleep infinity"
    #entrypoint: sleep 1h
    tty: true