version: '2.0'

services:
  master:
    image: dockersm
    environment:
      JAVA_OPTS: "-Djava.awt.headless=true"
    ports:
      - "5000:5000"
    volumes:
      - /var/jenkins_home
      - /var/run/docker.sock:/var/run/docker.sock
      - /usr/bin/docker:/usr/bin/docker
    working_dir: /dashboard/DSH-Smashing
    external_links:
      - dkafka
    container_name: dockersm
    entrypoint: bash -c "chmod u+x /dashboard/DSH-Smashing/runscript.sh && /dashboard/DSH-Smashing/runscript.sh"
    #entrypoint: sleep 1h