version: '2.0'

services:
  master:
    image: dockersm
    environment:
      JAVA_OPTS: "-Djava.awt.headless=true"
    ports:
      - "5000:5000"
    volumes:
      - /var/jenkins_home
      - /var/run/docker.sock:/var/run/docker.sock
      - /usr/bin/docker:/usr/bin/docker
    working_dir: /DSH-Smashing
    container_name: dockersm
    entrypoint: bash -lc "bundle && smashing start -p 5000 & sleep infinity && python3 py/kafkaConsumeSmashing.py -d"
    #entrypoint: sleep 1h
    tty: true